tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/core"
brew "awscli", link: false
brew "gobject-introspection"
brew "srt"
brew "ffmpeg"
brew "gh"
brew "ghq"
brew "git-secrets"
brew "goenv"
brew "grep"
brew "hugo"
brew "peco"
brew "pyenv"
brew "tcl-tk"
brew "python@3.8", link: false
brew "ruby-build"
brew "rbenv"
brew "tfenv"
brew "tmux"
brew "tree"
brew "yarn"
brew "zsh"

cask "1password"
cask "alfred"
cask "docker"
cask "Figma"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "slack"
cask "visual-studio-code"
